### ISSUE TITLE
Missing addition of input to interpolated position embedding

### ISSUE THREAD

**Issue by swarajnanda2021** [Sangh0/Self-Supervised-Learning#1]
In the file [`vit.py`](https://github.com/Sangh0/Self-Supervised-Learning/blob/main/DINO/models/vit.py), on [line 218](https://github.com/Sangh0/Self-Supervised-Learning/blob/main/DINO/models/vit.py#L218), I noticed that the position embeddings are not added to the patch embeddings after using the interpolation to the position embedding.

The following should help clarify the issue:

x += self.interpolate_pos_encoding(x, W, H)

**Comment by Sangh0** [comment]
@swarajnanda2021 Thank you for your feedback!
